package com.zyl.centre.entity;

// Generated 2015-12-13 14:43:40 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Activeshop generated by hbm2java
 */
@Entity
@Table(name = "activeshop", catalog = "beautycentre")
public class Activeshop implements java.io.Serializable {

	private ActiveshopId id;
	private Shop shop;
	private Imgactive imgactive;
	private String shopname;
	private String avtivename;

	public Activeshop() {
	}

	public Activeshop(ActiveshopId id, Shop shop, Imgactive imgactive) {
		this.id = id;
		this.shop = shop;
		this.imgactive = imgactive;
	}

	public Activeshop(ActiveshopId id, Shop shop, Imgactive imgactive,
			String shopname, String avtivename) {
		this.id = id;
		this.shop = shop;
		this.imgactive = imgactive;
		this.shopname = shopname;
		this.avtivename = avtivename;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "imgactiveid", column = @Column(name = "imgactiveid", nullable = false)),
			@AttributeOverride(name = "shopid", column = @Column(name = "shopid", nullable = false)) })
	public ActiveshopId getId() {
		return this.id;
	}

	public void setId(ActiveshopId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shopid", nullable = false, insertable = false, updatable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "imgactiveid", nullable = false, insertable = false, updatable = false)
	public Imgactive getImgactive() {
		return this.imgactive;
	}

	public void setImgactive(Imgactive imgactive) {
		this.imgactive = imgactive;
	}

	@Column(name = "shopname", length = 100)
	public String getShopname() {
		return this.shopname;
	}

	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	@Column(name = "avtivename", length = 50)
	public String getAvtivename() {
		return this.avtivename;
	}

	public void setAvtivename(String avtivename) {
		this.avtivename = avtivename;
	}

}
