package com.zyl.centre.entity;

// Generated 2015-12-25 13:47:12 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Complaint generated by hbm2java
 */
@Entity
@Table(name = "complaint", catalog = "beautycentre")
public class Complaint implements java.io.Serializable {

	private Integer complaintid;
	private Date createdatetime;
	private Date modifydatetime;
	private Integer submituserid;
	private String submitusername;
	private String complaintcontent;
	private String userphone;
	private Integer shopid;
	private String shopname;
	private Integer serviceid;
	private String servicename;
	private Integer state;
	private String feedback;
	private Integer dealuserid;
	private String dealusername;
	private Date dealdatetime;

	public Complaint() {
	}

	public Complaint(Date createdatetime, Date modifydatetime,
			Integer submituserid, String submitusername,
			String complaintcontent, String userphone, Integer shopid,
			String shopname, Integer serviceid, String servicename,
			Integer state, String feedback, Integer dealuserid,
			String dealusername, Date dealdatetime) {
		this.createdatetime = createdatetime;
		this.modifydatetime = modifydatetime;
		this.submituserid = submituserid;
		this.submitusername = submitusername;
		this.complaintcontent = complaintcontent;
		this.userphone = userphone;
		this.shopid = shopid;
		this.shopname = shopname;
		this.serviceid = serviceid;
		this.servicename = servicename;
		this.state = state;
		this.feedback = feedback;
		this.dealuserid = dealuserid;
		this.dealusername = dealusername;
		this.dealdatetime = dealdatetime;
	}

	public Integer getComplaintid() {
		return this.complaintid;
	}

	public void setComplaintid(Integer complaintid) {
		this.complaintid = complaintid;
	}

	public Date getCreatedatetime() {
		return this.createdatetime;
	}

	public void setCreatedatetime(Date createdatetime) {
		this.createdatetime = createdatetime;
	}

	public Date getModifydatetime() {
		return this.modifydatetime;
	}

	public void setModifydatetime(Date modifydatetime) {
		this.modifydatetime = modifydatetime;
	}

	public Integer getSubmituserid() {
		return this.submituserid;
	}

	public void setSubmituserid(Integer submituserid) {
		this.submituserid = submituserid;
	}

	public String getSubmitusername() {
		return this.submitusername;
	}

	public void setSubmitusername(String submitusername) {
		this.submitusername = submitusername;
	}

	public String getComplaintcontent() {
		return this.complaintcontent;
	}

	public void setComplaintcontent(String complaintcontent) {
		this.complaintcontent = complaintcontent;
	}

	public String getUserphone() {
		return this.userphone;
	}

	public void setUserphone(String userphone) {
		this.userphone = userphone;
	}

	public Integer getShopid() {
		return this.shopid;
	}

	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}

	public String getShopname() {
		return this.shopname;
	}

	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	public Integer getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}

	public String getServicename() {
		return this.servicename;
	}

	public void setServicename(String servicename) {
		this.servicename = servicename;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	public Integer getDealuserid() {
		return this.dealuserid;
	}

	public void setDealuserid(Integer dealuserid) {
		this.dealuserid = dealuserid;
	}

	public String getDealusername() {
		return this.dealusername;
	}

	public void setDealusername(String dealusername) {
		this.dealusername = dealusername;
	}

	public Date getDealdatetime() {
		return this.dealdatetime;
	}

	public void setDealdatetime(Date dealdatetime) {
		this.dealdatetime = dealdatetime;
	}

}
