package com.zyl.centre.entity;

// Generated 2015-12-13 14:43:40 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Imgactive generated by hbm2java
 */
@Entity
@Table(name = "imgactive", catalog = "beautycentre")
public class Imgactive implements java.io.Serializable {

	private Integer imgactiveid;
	private String activename;
	private String activeurl;
	private Date activeexpiredate;
	private Date activecreatedate;
	private String createusername;
	private String activedec;
	private String activeimgname;
	private String activeimgurl;
	private String ext1;
	private String ext2;
	private Set<Activeshop> activeshops = new HashSet<Activeshop>(0);

	public Imgactive() {
	}

	public Imgactive(String activename, String activeurl,
			Date activeexpiredate, Date activecreatedate,
			String createusername, String activedec, String activeimgname,
			String activeimgurl, String ext1, String ext2,
			Set<Activeshop> activeshops) {
		this.activename = activename;
		this.activeurl = activeurl;
		this.activeexpiredate = activeexpiredate;
		this.activecreatedate = activecreatedate;
		this.createusername = createusername;
		this.activedec = activedec;
		this.activeimgname = activeimgname;
		this.activeimgurl = activeimgurl;
		this.ext1 = ext1;
		this.ext2 = ext2;
		this.activeshops = activeshops;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "imgactiveid", unique = true, nullable = false)
	public Integer getImgactiveid() {
		return this.imgactiveid;
	}

	public void setImgactiveid(Integer imgactiveid) {
		this.imgactiveid = imgactiveid;
	}

	@Column(name = "activename", length = 50)
	public String getActivename() {
		return this.activename;
	}

	public void setActivename(String activename) {
		this.activename = activename;
	}

	@Column(name = "activeurl", length = 100)
	public String getActiveurl() {
		return this.activeurl;
	}

	public void setActiveurl(String activeurl) {
		this.activeurl = activeurl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "activeexpiredate", length = 0)
	public Date getActiveexpiredate() {
		return this.activeexpiredate;
	}

	public void setActiveexpiredate(Date activeexpiredate) {
		this.activeexpiredate = activeexpiredate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "activecreatedate", length = 0)
	public Date getActivecreatedate() {
		return this.activecreatedate;
	}

	public void setActivecreatedate(Date activecreatedate) {
		this.activecreatedate = activecreatedate;
	}

	@Column(name = "createusername", length = 50)
	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	@Column(name = "activedec", length = 65535)
	public String getActivedec() {
		return this.activedec;
	}

	public void setActivedec(String activedec) {
		this.activedec = activedec;
	}

	@Column(name = "activeimgname", length = 50)
	public String getActiveimgname() {
		return this.activeimgname;
	}

	public void setActiveimgname(String activeimgname) {
		this.activeimgname = activeimgname;
	}

	@Column(name = "activeimgurl", length = 100)
	public String getActiveimgurl() {
		return this.activeimgurl;
	}

	public void setActiveimgurl(String activeimgurl) {
		this.activeimgurl = activeimgurl;
	}

	@Column(name = "ext1", length = 30)
	public String getExt1() {
		return this.ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	@Column(name = "ext2", length = 40)
	public String getExt2() {
		return this.ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "imgactive")
	public Set<Activeshop> getActiveshops() {
		return this.activeshops;
	}

	public void setActiveshops(Set<Activeshop> activeshops) {
		this.activeshops = activeshops;
	}

}
