package com.zyl.centre.entity;

// Generated 2015-12-9 12:45:25 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;

/**
 * Imgadver generated by hbm2java
 */
public class Imgadver implements java.io.Serializable {

	private Integer imgadverid;
	private String advername;
	private String tourl;
	private String imgadvername;
	private String imgadverurl;
	private Date expiredate;
	private String refcityname;
	private Integer refcityid;
	private Date createdate;
	private Date modifydate;
	private String createop;
	private String modifyop;
	private String adverdec;
	private String ext1;
	private String ext2;

	public Imgadver() {
	}

	public Imgadver(String advername, String tourl, String imgadvername,
			String imgadverurl, Date expiredate, String refcityname,
			Integer refcityid, Date createdate, Date modifydate,
			String createop, String modifyop, String adverdec, String ext1,
			String ext2) {
		this.advername = advername;
		this.tourl = tourl;
		this.imgadvername = imgadvername;
		this.imgadverurl = imgadverurl;
		this.expiredate = expiredate;
		this.refcityname = refcityname;
		this.refcityid = refcityid;
		this.createdate = createdate;
		this.modifydate = modifydate;
		this.createop = createop;
		this.modifyop = modifyop;
		this.setAdverdec(adverdec);
		this.ext1 = ext1;
		this.ext2 = ext2;
	}

	public Integer getImgadverid() {
		return this.imgadverid;
	}

	public void setImgadverid(Integer imgadverid) {
		this.imgadverid = imgadverid;
	}

	public String getAdvername() {
		return this.advername;
	}

	public void setAdvername(String advername) {
		this.advername = advername;
	}

	public String getTourl() {
		return this.tourl;
	}

	public void setTourl(String tourl) {
		this.tourl = tourl;
	}

	public String getImgadvername() {
		return this.imgadvername;
	}

	public void setImgadvername(String imgadvername) {
		this.imgadvername = imgadvername;
	}

	public String getImgadverurl() {
		return this.imgadverurl;
	}

	public void setImgadverurl(String imgadverurl) {
		this.imgadverurl = imgadverurl;
	}

	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}

	public String getRefcityname() {
		return this.refcityname;
	}

	public void setRefcityname(String refcityname) {
		this.refcityname = refcityname;
	}

	public Integer getRefcityid() {
		return this.refcityid;
	}

	public void setRefcityid(Integer refcityid) {
		this.refcityid = refcityid;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	public String getCreateop() {
		return this.createop;
	}

	public void setCreateop(String createop) {
		this.createop = createop;
	}

	public String getModifyop() {
		return this.modifyop;
	}

	public void setModifyop(String modifyop) {
		this.modifyop = modifyop;
	}

	public String getExt1() {
		return this.ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	public String getExt2() {
		return this.ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

	@Column(name = "adverdec", length = 65535)
	public String getAdverdec() {
		return adverdec;
	}

	public void setAdverdec(String adverdec) {
		this.adverdec = adverdec;
	}

}
