package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "beautycentre")
public class Menu implements java.io.Serializable {

	private String menuId;
	private String menuName;
	private String parentId;
	private Integer levels;
	private String url;
	private Boolean checked;
	private String description;

	public Menu() {
	}

	public Menu(String menuId) {
		this.menuId = menuId;
	}

	public Menu(String menuId, String menuName, String parentId,
			Integer levels, String url, Boolean checked, String description) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.parentId = parentId;
		this.levels = levels;
		this.url = url;
		this.checked = checked;
		this.description = description;
	}

	@Id
	@Column(name = "menu_id", unique = true, nullable = false, length = 5)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menu_name", length = 50)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "parent_id", length = 5)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "levels")
	public Integer getLevels() {
		return this.levels;
	}

	public void setLevels(Integer levels) {
		this.levels = levels;
	}

	@Column(name = "url", length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "checked", precision = 1, scale = 0)
	public Boolean getChecked() {
		return this.checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
