package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "beautycentre")
public class Order implements java.io.Serializable {

	private Integer orderid;
	private User user;
	private Date createtime;
	private Date modifytime;
	private String submitusername;
	private Integer state;
	private String ordphone;
	private Integer number;
	private Integer sumprice;
	private Integer realprice;
	private Integer checkuserid;
	private String orderdec;
	private Set<Serviceordrel> serviceordrels = new HashSet<Serviceordrel>(0);

	public Order() {
	}

	public Order(User user) {
		this.user = user;
	}

	public Order(User user, Date createtime, Date modifytime,
			String submitusername, Integer state, String ordphone,
			Integer number, Integer sumprice, Integer realprice,
			Integer checkuserid, String orderdec,
			Set<Serviceordrel> serviceordrels) {
		this.user = user;
		this.createtime = createtime;
		this.modifytime = modifytime;
		this.submitusername = submitusername;
		this.state = state;
		this.ordphone = ordphone;
		this.number = number;
		this.sumprice = sumprice;
		this.realprice = realprice;
		this.checkuserid = checkuserid;
		this.orderdec = orderdec;
		this.serviceordrels = serviceordrels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orderid", unique = true, nullable = false)
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "submituserid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifytime", length = 0)
	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	@Column(name = "submitusername", length = 20)
	public String getSubmitusername() {
		return this.submitusername;
	}

	public void setSubmitusername(String submitusername) {
		this.submitusername = submitusername;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "ordphone", length = 32)
	public String getOrdphone() {
		return this.ordphone;
	}

	public void setOrdphone(String ordphone) {
		this.ordphone = ordphone;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "sumprice")
	public Integer getSumprice() {
		return this.sumprice;
	}

	public void setSumprice(Integer sumprice) {
		this.sumprice = sumprice;
	}

	@Column(name = "realprice")
	public Integer getRealprice() {
		return this.realprice;
	}

	public void setRealprice(Integer realprice) {
		this.realprice = realprice;
	}

	@Column(name = "checkuserid")
	public Integer getCheckuserid() {
		return this.checkuserid;
	}

	public void setCheckuserid(Integer checkuserid) {
		this.checkuserid = checkuserid;
	}

	@Column(name = "orderdec", length = 65535)
	public String getOrderdec() {
		return this.orderdec;
	}

	public void setOrderdec(String orderdec) {
		this.orderdec = orderdec;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Serviceordrel> getServiceordrels() {
		return this.serviceordrels;
	}

	public void setServiceordrels(Set<Serviceordrel> serviceordrels) {
		this.serviceordrels = serviceordrels;
	}

}
