package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prodtyperel generated by hbm2java
 */
@Entity
@Table(name = "prodtyperel", catalog = "beautycentre")
public class Prodtyperel implements java.io.Serializable {

	private ProdtyperelId id;
	private Service service;
	private Product product;
	private Prodtype prodtype;

	public Prodtyperel() {
	}

	public Prodtyperel(ProdtyperelId id, Service service, Product product,
			Prodtype prodtype) {
		this.id = id;
		this.service = service;
		this.product = product;
		this.prodtype = prodtype;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productid", column = @Column(name = "productid", nullable = false)),
			@AttributeOverride(name = "prodtypeid", column = @Column(name = "prodtypeid", nullable = false)),
			@AttributeOverride(name = "serviceid", column = @Column(name = "serviceid", nullable = false)) })
	public ProdtyperelId getId() {
		return this.id;
	}

	public void setId(ProdtyperelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false, insertable = false, updatable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prodtypeid", nullable = false, insertable = false, updatable = false)
	public Prodtype getProdtype() {
		return this.prodtype;
	}

	public void setProdtype(Prodtype prodtype) {
		this.prodtype = prodtype;
	}

}
