package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdtyperelId generated by hbm2java
 */
@Embeddable
public class ProdtyperelId implements java.io.Serializable {

	private int productid;
	private int prodtypeid;
	private int serviceid;

	public ProdtyperelId() {
	}

	public ProdtyperelId(int productid, int prodtypeid, int serviceid) {
		this.productid = productid;
		this.prodtypeid = prodtypeid;
		this.serviceid = serviceid;
	}

	@Column(name = "productid", nullable = false)
	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	@Column(name = "prodtypeid", nullable = false)
	public int getProdtypeid() {
		return this.prodtypeid;
	}

	public void setProdtypeid(int prodtypeid) {
		this.prodtypeid = prodtypeid;
	}

	@Column(name = "serviceid", nullable = false)
	public int getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(int serviceid) {
		this.serviceid = serviceid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdtyperelId))
			return false;
		ProdtyperelId castOther = (ProdtyperelId) other;

		return (this.getProductid() == castOther.getProductid())
				&& (this.getProdtypeid() == castOther.getProdtypeid())
				&& (this.getServiceid() == castOther.getServiceid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductid();
		result = 37 * result + this.getProdtypeid();
		result = 37 * result + this.getServiceid();
		return result;
	}

}
