package com.zyl.centre.entity;

// Generated 2015-12-19 18:01:22 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "beautycentre")
public class Review implements java.io.Serializable {

	private Integer reviewid;
	private Integer orderid;
	private Integer userid;
	private String username;
	private Integer ishopord;
	private Date createdatetime;
	private Integer score;
	private String content;
	private Date modifydatetime;
	private Integer shopid;
	private Integer serviceid;
	private String ext1;
	private String ext2;

	public Review() {
	}

	public Review(Integer orderid, Integer userid, String username,
			Integer ishopord, Date createdatetime, Integer score,
			String content, Date modifydatetime, Integer shopid,
			Integer serviceid, String ext1, String ext2) {
		this.orderid = orderid;
		this.userid = userid;
		this.username = username;
		this.ishopord = ishopord;
		this.createdatetime = createdatetime;
		this.score = score;
		this.content = content;
		this.modifydatetime = modifydatetime;
		this.shopid = shopid;
		this.serviceid = serviceid;
		this.ext1 = ext1;
		this.ext2 = ext2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reviewid", unique = true, nullable = false)
	public Integer getReviewid() {
		return this.reviewid;
	}

	public void setReviewid(Integer reviewid) {
		this.reviewid = reviewid;
	}

	@Column(name = "orderid")
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "userid")
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "username", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "ishopord")
	public Integer getIshopord() {
		return this.ishopord;
	}

	public void setIshopord(Integer ishopord) {
		this.ishopord = ishopord;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdatetime", length = 0)
	public Date getCreatedatetime() {
		return this.createdatetime;
	}

	public void setCreatedatetime(Date createdatetime) {
		this.createdatetime = createdatetime;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifydatetime", length = 0)
	public Date getModifydatetime() {
		return this.modifydatetime;
	}

	public void setModifydatetime(Date modifydatetime) {
		this.modifydatetime = modifydatetime;
	}

	@Column(name = "shopid")
	public Integer getShopid() {
		return this.shopid;
	}

	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}

	@Column(name = "serviceid")
	public Integer getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}

	@Column(name = "ext1", length = 30)
	public String getExt1() {
		return this.ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	@Column(name = "ext2", length = 40)
	public String getExt2() {
		return this.ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

}
