package com.zyl.centre.entity;
// Generated 2015-12-10 14:18:46 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Serviceordrel generated by hbm2java
 */
public class Serviceordrel  implements java.io.Serializable {


     private ServiceordrelId id;
     private Order order;
     private Date date;
     private String ext1;

    public Serviceordrel() {
    }

	
    public Serviceordrel(ServiceordrelId id, Order order) {
        this.id = id;
        this.order = order;
    }
    public Serviceordrel(ServiceordrelId id, Order order, Date date, String ext1) {
       this.id = id;
       this.order = order;
       this.date = date;
       this.ext1 = ext1;
    }
   
    public ServiceordrelId getId() {
        return this.id;
    }
    
    public void setId(ServiceordrelId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
}

