package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Shopcity generated by hbm2java
 */
@Entity
@Table(name = "shopcity", catalog = "beautycentre")
public class Shopcity implements java.io.Serializable {

	private ShopcityId id;

	public Shopcity() {
	}

	public Shopcity(ShopcityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "shopid", column = @Column(name = "shopid", nullable = false)),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 20)) })
	public ShopcityId getId() {
		return this.id;
	}

	public void setId(ShopcityId id) {
		this.id = id;
	}

}
