package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Shopordcunt generated by hbm2java
 */
@Entity
@Table(name = "shopordcunt", catalog = "beautycentre")
public class Shopordcunt implements java.io.Serializable {

	private ShopordcuntId id;

	public Shopordcunt() {
	}

	public Shopordcunt(ShopordcuntId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "shopid", column = @Column(name = "shopid", nullable = false)),
			@AttributeOverride(name = "ordcount", column = @Column(name = "ordcount", nullable = false)),
			@AttributeOverride(name = "orddate", column = @Column(name = "orddate", length = 0)) })
	public ShopordcuntId getId() {
		return this.id;
	}

	public void setId(ShopordcuntId id) {
		this.id = id;
	}

}
