package com.zyl.centre.entity;

// Generated 2015-11-17 16:17:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShopcityId generated by hbm2java
 */
@Embeddable
public class ShopcityId implements java.io.Serializable {

	private int shopid;
	private String city;

	public ShopcityId() {
	}

	public ShopcityId(int shopid) {
		this.shopid = shopid;
	}

	public ShopcityId(int shopid, String city) {
		this.shopid = shopid;
		this.city = city;
	}

	@Column(name = "shopid", nullable = false)
	public int getShopid() {
		return this.shopid;
	}

	public void setShopid(int shopid) {
		this.shopid = shopid;
	}

	@Column(name = "city", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopcityId))
			return false;
		ShopcityId castOther = (ShopcityId) other;

		return (this.getShopid() == castOther.getShopid())
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null
						&& castOther.getCity() != null && this.getCity()
						.equals(castOther.getCity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getShopid();
		result = 37 * result
				+ (getCity() == null ? 0 : this.getCity().hashCode());
		return result;
	}

}
